const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, 'en.html');
let html = fs.readFileSync(file, 'utf8');

const dictionary = {
  '이제 한국의 치기공 퀄리티를<br>전 세계에서<br><em>만날 수 있습니다.</em>': 'Experience Korean Dental Lab Quality<br>Now Available<br><em>Worldwide.</em>',
  '디지털 스캔-투-밀 워크플로우, 전 케이스 시니어 QC 검수.': 'Digital scan-to-mill workflow with senior QC for every case.',
  '원장님의 삭제 스타일, 쉐이드, 컨택 방식을 학습한 한 명의 기공사가 매 케이스 담당.': 'A dedicated technician who learns your prep style, shade, and contact preferences.',
  'Custom Abutment 포함 가격. 국내 평균 대비 합리적인 수가로 병원 수익성을 높여드립니다.': "Custom Abutment included. Maximize your clinic's profitability with highly competitive pricing.",
  '월요일 스캔 전송, 다음 주 금요일 장착 가능. 배송비 포함. 단계별 진행 상황 실시간 업데이트.': 'Scan on Monday, seat by next Friday. Shipping included. Real-time updates at every stage.',
  '원장님 진료에<br>필요한 <em>모든 것.</em>': 'Everything Your Practice<br><em>Needs.</em>',
  '전체 가격표 요청하기': 'Request Full Price List',
  '지르코니아, PFZ, e.max, PFM. Custom Abutment 포함. 14개 이상 임플란트 시스템 지원.': 'Zirconia, PFZ, e.max, PFM. Custom Abutment included. Supports 14+ implant systems.',
  '단관 크라운, 3본~장스팬 브릿지, 인레이·온레이. 지르코니아 또는 e.max.': 'Single crowns, 3-unit to long-span bridges, inlays/onlays. Zirconia or e.max.',
  '전악 고정성 보철. 12 또는 14유닛. 지르코니아 밀링 또는 레이어드.': 'Full arch fixed prosthetics. 12 or 14 units. Zirconia milled or layered.',
  '핸드프레스 e.max 베니어. 심미 전문 기공사 담당. 3D 왁스업 무료 제공.': 'Hand-pressed e.max veneers handled by esthetic specialists. Free 3D wax-up provided.',
  'Trista 또는 Scheu 소재. 전악 또는 편악. 리파인먼트 1세트 무료 포함.': 'Trista or Scheu materials. Full or partial arch. 1 set of refinement included for free.',
  '교합 스플린트, 나이트가드, 수면무호흡 장치, 디지털 의치.': 'Occlusal splints, night guards, sleep apnea devices, digital dentures.',
  '원장님이 사용하시는 임플란트(오스템, 덴티움 등)에 맞는 스캔바디 세트를 무상으로 지원/대여해 드립니다.': 'Free provision/rental of scan body kits tailored to your preferred implant system (Osstem, Dentium, etc.).',
  '병원별 의뢰 통계, 지출 내역, 환자 스캔 데이터 통합 관리를 원장님 전용 웹/앱으로 제공. (무상)': 'Integrated management of lab statistics, expenses, and patient scan data via a dedicated web/app. (Free)',
  'VIP 환자를 위한 긴급 제작 라인. 기본 10일 소요 기간을 48시간 내로 단축하여 발송합니다.': 'Emergency production line for VIP patients. Shortens the standard 10-day turnaround to within 48 hours.',
  '스캔, 전송,<br><em>장착.</em>': 'Scan, Send,<br><em>Seat.</em>',
  'Medit, Trios, Primescan, iTero 등 — 스캔 파일을 포털에 업로드하시면 됩니다. 파일 형식 설정은 저희가 안내해드립니다.': "Medit, Trios, Primescan, iTero, etc. — simply upload the files to our portal. We'll guide you on file formats.",
  '쉐이드, 마진 종류, 컨택 방식, 이머전스 프로파일 — 한 번 등록하면 모든 케이스에 자동 적용됩니다.': 'Shade, margin type, contact style, emergence profile — register once, automatically applied to all cases.',
  '담당 기공사가 밀링 전 3D 디자인 미리보기를 전송합니다. 승인 또는 수정 요청 — 원장님이 결정하세요.': 'Your tech sends a 3D design preview before milling. Approve or request changes — you are in control.',
  '10 영업일, 제작 완료 후 배송까지. 단계별 진행 상황 업데이트.': '10 business days from fabrication to delivery. Real-time updates at every step.',
  '어려운 치과 용어도<br>아무 어려움 없이<br><em>소통 가능</em>': 'Communicate Complex<br>Dental Terms With<br><em>Zero Barrier</em>',
  '전 케이스 시니어 QC': 'Senior QC on Every Case',
  'ISO 인증 소재': 'ISO Certified Materials',
  '<strong>평균 15년 이상의 마스터 팀</strong> — 단순 기공사가 아닌 각 분야(심미, 풀아치, 임플란트)의 수석 마스터들이 원장님의 케이스를 직접 책임집니다.': '<strong>Master Team with 15+ Years Avg. Experience</strong> — Senior masters in esthetics, full arch, and implants take full responsibility for your cases.',
  '<strong>타협 없는 소재 선택</strong> — 저희 환자에게 쓰는 것과 동일한 Grade-A 소재만 사용합니다. 비용을 이유로 소재를 바꾸지 않습니다.': '<strong>Uncompromising Materials</strong> — We use the same Grade-A materials as we do for our own patients. We never cut corners on materials to save costs.',
  '<strong>전 케이스 시니어 QC</strong> — 발송 전 수석 기공사가 마진 적합도, 쉐이드, 교합 접촉을 직접 확인합니다.': '<strong>Senior QC on Every Case</strong> — Before shipping, senior technicians meticulously verify margin fit, shade, and occlusal contacts.',
  '<strong>3D 디자인 미리보기</strong> — 밀링 전 원장님이 직접 디자인을 검토하고 수정을 요청할 수 있습니다.': '<strong>3D Design Preview</strong> — Review the design yourself and request modifications prior to milling.',
  '원장님들의 이야기': 'Dentist Testimonials',
  '결과가<br><em>증명합니다.</em>': 'The Results<br><em>Speak for Themselves.</em>',
  '첫 번에 바로 장착됐습니다. 마진이 깔끔하고 조정이 전혀 필요 없었어요. 이런 게 제대로 만든 보철이구나 싶었습니다.': 'Seated perfectly on the first try. Margins were pristine and zero adjustments were needed. This is what a proper prosthetic feels like.',
  '김** 원장': 'Dr. Kim',
  '서울 서초구 · 개원 치과': 'Private Practice, NY',
  '기공소를 여러 군데 써봤는데, 리메이크가 없어진 건 블랑쉬랩으로 바꾸고 나서부터입니다. 담당 기공사가 생기니 소통도 훨씬 쉬워요.': "I've tried many labs, but remakes disappeared only after switching to DentAi. Having a dedicated tech makes communication so much easier.",
  '이** 원장': 'Dr. Lee',
  '경기도 분당 · 치과 의원': 'Dental Clinic, CA',
  '상단 전치부 단관이 얼마나 까다로운지 아시잖아요. 쉐이드 매칭이 완벽했습니다. 환자분도 매우 만족하셨어요.': 'You know how tricky anterior single crowns can be. The shade match was flawless. The patient was extremely satisfied.',
  '박** 원장': 'Dr. Park',
  '서울 마포구 · 심미 치과': 'Esthetic Clinic, VA',
  '궁금한 점이<br><em>있으신가요?</em>': 'Have Any<br><em>Questions?</em>',
  '리메이크 시 배송비나 추가 비용이 있나요?': 'Are there shipping or additional costs for remakes?',
  '아니요. 장착 불량 등의 이유로 리메이크가 발생할 경우, 24hr 내 무상 재제작은 물론 왕복 배송비까지 모두 블랑쉬랩에서 부담합니다.': 'No. If a remake is necessary due to fit issues, we provide free remanufacturing within 24 hours and cover all round-trip shipping costs.',
  '어떤 구강 스캐너와 호환되나요?': 'Which intraoral scanners are compatible?',
  'Medit, 3Shape Trios, Primescan, iTero 등 시중의 모든 주요 구강 스캐너의 STL, PLY 형태 파일을 지원합니다. 지정된 파일 전송 포털을 통해 간편하게 업로드할 수 있습니다.': 'We support STL and PLY files from all major intraoral scanners, including Medit, 3Shape Trios, Primescan, and iTero. You can easily upload them through our dedicated portal.',
  '첫 케이스 무료 혜택은 어떤 보철물에 적용되나요?': 'Which prosthetics are eligible for the free first case?',
  'Implant Crown(Custom Abutment 포함), 단관 크라운, 브릿지, 베니어 중 원장님이 테스트해보고 싶으신 케이스 1건을 비용 없이 진행해 드립니다.': 'You can try one case for free from Implant Crown (Custom Abutment included), single crown, bridge, or veneer.',
  '스캔바디 키트는 무료로 제공되나요?': 'Are scan body kits provided for free?',
  '네, 거래를 시작하시면 원장님이 주로 사용하시는 임플란트 시스템에 맞는 정밀 스캔바디 키트를 치과로 무상 대여 및 발송해 드립니다.': 'Yes, once we start working together, we will dispatch complimentary precision scan body kits that match your preferred implant systems.',
  '지금 시작하기': 'Get Started Now',
  '첫 케이스는<br><em>저희가 냅니다.</em>': 'Your First Case<br><em>is on Us.</em>',
  '카드 등록 불필요, 계약 없음, 최소 수량 없음. 케이스 한 건을 먼저 경험해보시고 판단하세요.': 'No credit card required, no contracts, no minimums. Experience one case first, then decide.',
  '<strong>첫 케이스 완전 무료</strong> — Implant Crown, 브릿지, 베니어 중 선택': '<strong>First Case Completely Free</strong> — Choose from Implant Crown, Bridge, or Veneer',
  '<strong>스캔바디 키트 무료 발송</strong> — 치과로 직접 배송': '<strong>Free Scan Body Kit</strong> — Delivered directly to your clinic',
  '<strong>1:1 Designated Lab Tech 즉시 배정</strong> — 첫날부터 같은 기공사가 담당': '<strong>1:1 Designated Lab Tech Immediately</strong> — Same tech handles your cases from day one',
  '<strong>무상 리메이크 보증</strong> — 장착 불량 시 24hr 내 재제작': '<strong>Free Remake Guarantee</strong> — Remade within 24hr for fit issues',
  '<strong>10일 납기</strong> — 배송비 포함, 단계별 진행 알림': '<strong>10-Day Turnaround</strong> — Shipping included, step-by-step alerts',
  '케이스 의뢰 신청': 'Submit a Case Request',
  '24hr 내 전담 기공사가 배정되어 연락드립니다.': 'A designated lab tech will be assigned and contact you within 24 hours.',
  '성 <span class="req">*</span>': 'Last Name <span class="req">*</span>',
  '이름 <span class="req">*</span>': 'First Name <span class="req">*</span>',
  '김': 'Smith',
  '민준': 'John',
  '연락처 (휴대폰)': 'Phone Number',
  '치과 상호 <span class="req">*</span>': 'Clinic Name <span class="req">*</span>',
  '○○치과의원': 'ABC Dental Clinic',
  '지역': 'State / Region',
  '지역 선택': 'Select Region',
  '서울 서초/서초': 'New York',
  '서울 강북/도심': 'California',
  '서울 기타': 'Texas',
  '경기 (수도권)': 'Florida',
  '부산/경남': 'Illinois',
  '대구/경북': 'Pennsylvania',
  '인천': 'Ohio',
  '광주/전남': 'Georgia',
  '대전/충청': 'North Carolina',
  '기타 지방': 'Other',
  '사용 중인 구강 스캐너': 'Intraoral Scanner Model',
  '스캐너 선택': 'Select Scanner',
  '인상 채득 (아날로그)': 'Physical Impression (Analog)',
  '기타 / 미사용': 'Other / Not Using',
  '첫 케이스 보철 종류 <span class="req">*</span>': 'First Case Prosthetic Type <span class="req">*</span>',
  '단관 크라운': 'Single Crown',
  '브릿지': 'Bridge',
  '베니어': 'Veneer',
  '투명교정 장치': 'Clear Aligner',
  '기타': 'Other',
  '스캔 파일 <span style="color:var(--text-muted); font-size:11px; font-weight:400;">(선택 — 나중에 Email로도 가능)</span>': 'Scan Files <span style="color:var(--text-muted); font-size:11px; font-weight:400;">(Optional — can be emailed later)</span>',
  '스캔 파일을 여기에 끌어다 놓거나 클릭하세요': 'Drag and drop scan files here or click to upload',
  '최대 200MB': 'Max 200MB',
  '케이스 특이사항 / 요청사항': 'Case Notes / Special Requests',
  '쉐이드, 마진 종류, 기타 요청사항을 자유롭게 적어주세요...': 'Please write shade, margin preferences, and any other requests freely...',
  '개인정보는 케이스 진행 목적으로만<br>사용되며 제3자에게 제공되지 않습니다.': 'Personal information is used solely for processing your case and will not be shared with third parties.',
  '신청하기': 'Submit Request',
  '신청이 접수되었습니다.': 'Request Submitted.',
  '<strong>Email을 확인해 주세요</strong> — 접수 확인서와 다음 단계 안내를 보내드렸습니다.': '<strong>Please check your email</strong> — We have sent a confirmation and next steps.',
  '블랑쉬치과 직영 인하우스 기공소.<br>서울 서초에서 정밀 보철물을 제작합니다.': 'In-house lab directly operated by top clinics. Crafting precision prosthetics in Seoul.',
  '크라운 & 브릿지': 'Crown & Bridge',
  '투명교정': 'Clear Aligners',
  '회사 정보': 'Company Info',
  '가격표': 'Price List',
  '스캔바디 키트 요청': 'Request Scan Body Kit',
  '상담 예약': 'Book a Consultation',
  '블랑쉬치과': 'Blanche Dental Clinic',
  '직영 · 서울특별시 서초구': 'Operated · Seoul, Korea',
  '신청이 완료되었습니다!': 'Submission Complete!',
  '가장 많이 찾으시는': 'Most Popular',
  '보철': 'Prosthetics',
  '풀아치': 'Full Arch',
  '심미': 'Esthetics',
  '교정': 'Orthodontics',
  '기타 장치': 'Other Devices',
  '신규 거래처 혜택': 'New Client Benefit',
  '무상 지원': 'Complimentary',
  '출시 예정': 'Coming Soon',
  '프로토타입 구경하기 →': 'View Prototype →',
  '수가 + 20%': 'Base Price + 20%',
  '진행 방법 보기': 'See How It Works',
  '현재 제작 중인 케이스': 'Cases Currently in Production',
  '김** 원장님 · #16 Implant Crown': 'Dr. Kim · #16 Implant Crown',
  '지르코니아 · Custom Abutment': 'Zirconia · Custom Abutment',
  '밀링 중': 'Milling',
  '박** 원장님 · 베니어 ×6': 'Dr. Park · Veneers ×6',
  'e.max · 전치부 심미': 'e.max · Anterior Esthetics',
  'QC 검수': 'QC Inspection',
  '이** 원장님 · 3본 브릿지': 'Dr. Lee · 3-unit Bridge',
  '발송 완료': 'Shipped',
  '최** 원장님 · 풀아치': 'Dr. Choi · Full Arch',
  'All-on-X · 지르코니아 14유닛': 'All-on-X · Zirconia 14 units',
  '디자인 검토': 'Design Review',
  '스캐너 무관 · 계약 없음 · 최소 수량 없음': 'Any Scanner · No Contracts · No Minimums',
  '리메이크율': 'Remake Rate',
  '납기 (배송 포함)': 'Turnaround (incl. Shipping)',
  '제작 ~ 배송 완료': 'Fabrication ~ Delivery',
  '첫 케이스 무료': 'First Case Free',
  'Services표': 'Services',
  '유닛': 'unit',
  '아치': 'arch'
};

for (const [ko, en] of Object.entries(dictionary)) {
  html = html.split(ko).join(en);
}

fs.writeFileSync(file, html, 'utf8');
console.log('Translation complete.');
